steps:
  # Step 1: Install Composer dependencies
  - name: 'gcr.io/cloud-builders/composer'
    args: ['install', '--no-dev', '--prefer-dist']

  # Step 2: SSH into VM and deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh alkasima@oposchat --zone us-central1-a --command="
          cd /var/www/oposchat &&
          git pull origin main &&
          composer install --no-dev --prefer-dist &&
          php artisan migrate --force &&
          sudo chown -R www-data:www-data /var/www/oposchat
        "

# Optional: set timeout if migrations or composer take long
timeout: '1200s'
